---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-tmp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:capi-system:capi-manager
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:capi-kubeadm-control-plane-system:capi-kubeadm-control-plane-manager
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:capi-kubeadm-bootstrap-system:capi-kubeadm-bootstrap-manager
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:capa-system:capa-controller-manager
